import { defineSchema } from '../engine';

export const JOB_APPLICATION = defineSchema({
  $schema: 'sfb/v1',
  id: 'jobApplication',
  title: 'Job application',
  description: 'A four-step wizard: dependent async selects, conditional fields, a repeatable list with date ranges.',
  submitLabel: 'Send application',
  fields: [
    {
      type: 'step',
      id: 'about',
      title: 'About you',
      fields: [
        { type: 'text', key: 'fullName', label: 'Full name', width: 'half', rules: { required: true, minLength: 2 } },
        { type: 'email', key: 'email', label: 'Email', width: 'half', rules: { required: true } },
        { type: 'phone', key: 'phone', label: 'Phone', mask: '+1 (###) ###-####', width: 'half' },
        {
          type: 'text',
          key: 'profileUrl',
          label: 'Portfolio or GitHub URL',
          width: 'half',
          placeholder: 'https://',
          rules: { pattern: { regex: '^https://\\S+$', message: 'Must start with https://' } },
        },
        {
          type: 'select',
          key: 'country',
          label: 'Country',
          width: 'half',
          optionsSource: { provider: 'countries' },
          rules: { required: true },
        },
        {
          type: 'select',
          key: 'city',
          label: 'City',
          width: 'half',
          hint: 'Loaded for the selected country.',
          optionsSource: { provider: 'cities', params: 'country' },
          enabledWhen: '!empty(country)',
          rules: { required: true },
        },
      ],
    },
    {
      type: 'step',
      id: 'experience',
      title: 'Experience',
      fields: [
        {
          type: 'select',
          key: 'role',
          label: 'Role you apply for',
          width: 'half',
          options: [
            { value: 'frontend', label: 'Frontend engineer' },
            { value: 'fullstack', label: 'Full-stack engineer' },
            { value: 'lead', label: 'Tech lead' },
            { value: 'other', label: 'Other…' },
          ],
          rules: { required: true },
        },
        {
          type: 'text',
          key: 'otherRole',
          label: 'Which role?',
          width: 'half',
          visibleWhen: "role == 'other'",
          rules: { required: true },
        },
        { type: 'number', key: 'years', label: 'Years of experience', width: 'half', rules: { required: true, min: 0, max: 50 } },
        {
          type: 'multiselect',
          key: 'skills',
          label: 'Skills',
          hint: 'Pick at least two.',
          options: [
            { value: 'angular', label: 'Angular' },
            { value: 'rxjs', label: 'RxJS' },
            { value: 'signals', label: 'Signals' },
            { value: 'ngxs', label: 'NGXS / NgRx' },
            { value: 'typescript', label: 'TypeScript' },
            { value: 'testing', label: 'Testing' },
          ],
          rules: { required: true, minLength: 2, messages: { minLength: 'Pick at least two skills' } },
        },
        {
          type: 'repeat',
          key: 'positions',
          label: 'Previous positions',
          itemLabel: 'Position',
          minItems: 1,
          maxItems: 5,
          fields: [
            { type: 'text', key: 'company', label: 'Company', width: 'half', rules: { required: true } },
            { type: 'text', key: 'title', label: 'Title', width: 'half', rules: { required: true } },
            { type: 'date-range', key: 'period', label: 'Period', startLabel: 'From', endLabel: 'To', rules: { required: true } },
          ],
        },
      ],
    },
    {
      type: 'step',
      id: 'preferences',
      title: 'Preferences',
      fields: [
        {
          type: 'date',
          key: 'availableFrom',
          label: 'Available from',
          width: 'half',
          rules: { required: true, validators: [{ name: 'futureDate' }] },
        },
        { type: 'number', key: 'salary', label: 'Expected salary (yearly)', prefix: '€', step: 1000, width: 'half', rules: { min: 0 } },
        {
          type: 'radio',
          key: 'workMode',
          label: 'Work mode',
          options: [
            { value: 'remote', label: 'Remote' },
            { value: 'hybrid', label: 'Hybrid' },
            { value: 'office', label: 'Office' },
          ],
          rules: { required: true },
        },
        { type: 'switch', key: 'relocate', label: 'Open to relocation', visibleWhen: "workMode != 'remote'" },
        {
          type: 'text',
          key: 'relocationCity',
          label: 'Preferred city',
          visibleWhen: "relocate && workMode != 'remote'",
          rules: { required: true },
        },
      ],
    },
    {
      type: 'step',
      id: 'finish',
      title: 'Finish',
      fields: [
        { type: 'file', key: 'cv', label: 'CV (PDF)', accept: '.pdf', maxSizeMb: 5, hint: 'Stays in your browser — only name and size are kept.', rules: { required: true } },
        { type: 'textarea', key: 'coverLetter', label: 'Cover letter', rows: 5, rules: { maxLength: 1000 } },
        { type: 'rating', key: 'formRating', label: 'How was this form?', scale: 5 },
        { type: 'checkbox', key: 'consent', label: 'I agree to the processing of my data for this application', rules: { required: true } },
      ],
    },
  ],
});
